### ISSUE TITLE
Sistemare show-hide pagina Album.

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#1]
Ci sono un po' di problemi con questa pagina:

* I link "mostra testo" vengono visualizzati anche quando non dovrebbero, ad esempio nei browser testuali e nel browser normale quando javascript viene disattivato. 

* Al momento la pagina non è granché accessibile, ad esempio uno screen reader vede tutti i testi di fila, non c'è modo di saltare da un testo all'altro o da un album all'altro, inoltre questo screen reader in teoria vede sia il link alla pagina esterna dei testi e poi tutti i testi sulla stessa pagina. Insomma è un casino.

Possibile soluzione a entrambi i problemi:

* Sistemare lo script javascript in modo che aggiunga lui i vari link e dati necessari. Penso che per far questo basti impostare l'xslt in modo che aggiunga soltanto i div necessari al contenimento di link e testi e poi da javascript accedere a questi div tramite l'id e buttare dentro i dati necessari. Per far questo potrebbe essere necessario scavare nell'xml da javascript, potrebbe essere utile questo (http://www.w3schools.com/dom/dom_nodes_get.asp) ci ho dato solo un occhio veloce ma mi sembra adatto.

In questo modo la pagina senza javascript sarebbe pulita, senza testi ecc. e questo sistema i casini sia con gli screen reader che con i browser testuali e i browser con javascript disattivato.

**Comment by inrace** [comment]
mi ci metterò Lunedì, ergo speriamo non ci siano grossi problemi

**Comment by acavestro** [comment]
La soluzione più semplice che mi è venuta in mente è:

* mettiamo i testi della pagina album dentro a un div con una classe css visibile solo a chi accede tramite browser normale (nel css di default sarà ad esempio ````display:block;```` mentre in quello accessibile sarà ````display:none;````)
* stessa cosa per i link mostra testo
* se vogliamo mostrare roba in più visibile solo da screenreader c'è la classe css .access già pronta.
* se bisogna far saltare uno screenreader si possono usare ancore (se funzionano)

Non usiamo javascript per fare queste cose che viene su il disastro. :warning:

**Comment by inrace** [comment]
Quindi togliere del tutto javascrip?
Il 26/giu/2015 15:03, "acavestro" <notifications@github.com> ha scritto:

**Comment by acavestro** [comment]
Mi sembra molto più semplice che iniettare cose in giro con javascript.
Anche se magari meno sicuro (metti che ci sarà qualche screenreader che legge lo stesso gli elementi con ````display:none;````).

Tu che dici?

**Comment by acavestro** [comment]
@gpozzan Ho buttato su un css per screenreader e terminali che dovrebbe fare quello che chiedi.
Almeno, sull'emulatore di Chrome è così.

Il mio browser testuale (elinks) fa di testa sua non sembra riconoscere la media query.

**Comment by inrace** [comment]
Non ci siamo, links2 mostra sempre i testi e se premi su mostra testo finisci in una pagina 404.
non mi è nemmeno chiaro come faccia a mostrare sempre i testi sinceramente .....

anche con chrome e javascript disattivato la situazione non è perfetta perchè mostra i testi tutti attaccati, allego qualche screen

**Comment by acavestro** [comment]
Lo so, la situazione è un po' complicata.

Ho fatto una modifica (e14f2c2) in modo da togliere i pulsanti se non c'è JS però il problema coi browser testuali rimane: non capisco che cazzo facciano, hanno una cache assurda e sembrano mischiare plain text con un po' di CSS.

Proverei con uno screen reader. Io da chrome, col simulatore del media, vedo così:
![schermata 2015-06-30 alle 22 33 07](https://cloud.githubusercontent.com/assets/6882005/8441489/de41251e-1f78-11e5-9808-e7929b102629.png)

**Comment by inrace** [comment]
Anche con chrome rimangono, solo che non sono clickabili, o forse hai fatto
la modifica tipo negl'ultimi 30 min e devo ancora aggiornare?

In ogni caso una volta mostrati tutti i testi manca il tasto per
nosconderli (quando javascript è disattivato intendo)

Poi provo con firefox, solo che li non si può più togliere javascript
quindi devo trovare qualche maniera strana per farlo......
Non so se abbia senso visto che non è più disattivabile, ma magari qualcuno
ha una versione vecchia con javascript disattivato (ehm Nicola) e quindi
meglio controlalre credo.

Il giorno 30 giugno 2015 22:40, acavestro <notifications@github.com> ha
scritto:

**Comment by inrace** [comment]
Vi sono arrivati gli screen prima?
per sicurezza li allego qui

Il giorno 30 giugno 2015 22:48, Mattia Buso <mattia.buso@gmail.com> ha
scritto:

**Comment by fsestini** [comment]
A me su lynx mostra il "bottone" per mostrare i testi, ma i testi vengono già mostrati tutti.
Al tentativo di attivare il link mi viene dato l'errore che vedete.

![screen shot 2015-06-30 at 10 58 18 pm](https://cloud.githubusercontent.com/assets/9115681/8441892/8aff1c1e-1f7b-11e5-9c7a-07a5f7519734.png)

Also, non dovremmo avere un menu che permette di saltare alla canzone desiderata senza che lo screen reader debba leggere n-1 testi per arrivare all'n-esimo?

**Comment by acavestro** [comment]
>Anche con chrome rimangono, solo che non sono clickabili, o forse hai fatto
>la modifica tipo negl'ultimi 30 min e devo ancora aggiornare?

Fatta poco fa, prova ad aggiornare.

>A me su lynx mostra il "bottone" per mostrare i testi, ma i testi vengono già mostrati tutti.
>Al tentativo di attivare il link mi viene dato l'errore che vedete.

Lo so, ma purtroppo non trovo soluzione.

>Also, non dovremmo avere un menu che permette di saltare alla canzone desiderata senza che lo >screen reader debba leggere n-1 testi per arrivare all'n-esimo?

Si potrebbero aggiungere delle ancore. Domani faccio.

**Comment by inrace** [comment]
a me uguale solo che invece che dare un errore così mi mostra una nuova
pagina con errore 404

(se guardi c'è pure "testi" che te li mostra tutti assieme come quando
javascript è disattivato)

Il giorno 30 giugno 2015 23:00, Filippo Sestini <notifications@github.com>
ha scritto:

**Comment by fsestini** [comment]
> On Jun 30, 2015, at 11:06 PM, inrace <notifications@github.com> wrote:
> 
> a me uguale solo che invece che dare un errore così mi mostra una nuova
> pagina con errore 404
> 
> (se guardi c'è pure "testi" che te li mostra tutti assieme come quando
> javascript è disattivato)

Io farei così:
* javascript: normale
* no javascript: mostra tutti i testi
* screen reader/testuale: menu di selezione del singolo testo, e link in fondo ad ogni testo per tornare al menu (o a inizio pagina). In questo modo uno screen reader che fa menu -> testo k non deve refreshare o leggere i restanti n-k prima di tornare in cima.

— 
Filippo Sestini
sestini.filippo@gmail.com
(+39) 333 6757668

**Comment by inrace** [comment]
Ok con chrome risolto! Bravo

Per lynks considerando che a Filippo da un errore non grave direi che
possiamo anche tirare avanti così.



Il giorno 30 giugno 2015 23:06, Mattia Buso <mattia.buso@gmail.com> ha
scritto:

**Comment by fsestini** [comment]
Strano comunque che venga fuori "mostra testo" su lynx che neanche supporta JS

**Comment by inrace** [comment]
molto più strano che li mostri, mi sa che lo supporta ma male

2015-06-30 23:18 GMT+02:00 Filippo Sestini <notifications@github.com>:

**Comment by inrace** [comment]
WTF, ora chrome mi mostra il "mostra testo" dopo aver riattivato javascript
ho refreshato diverse volte ma non me li mostrava....

Quindi torniamo al Bravo.

Il giorno 30 giugno 2015 23:25, Mattia Buso <mattia.buso@gmail.com> ha
scritto:

**Comment by gpozzan** [comment]
Mattia non so se abbiamo versioni diverse di firefox comunque per
disattivare javascript a me basta scrivere "about:config" nella barra degli
indirizzi e mi si apre una schermata sulla quale c'è una linea "javascript:
enabled" che basta cliccare per impostare a false e si disattiva.

2015-06-30 23:35 GMT+02:00 inrace <notifications@github.com>:

**Comment by inrace** [comment]
Ah grazie, si anche nel mio funziona.
Non c'é più un vero e proprio tasto come su chrome, peró immaginavo ci
fosse qualche modo strano.
In ogni caso ho trovato un plugin che lo disattiva ed é molto comodo perché
basta premere un tasto, se puó servirvi si chiama Noscript
Il 01/lug/2015 07:27, "gpozzan" <notifications@github.com> ha scritto:

**Comment by acavestro** [comment]
Mi sono perso: almeno disabilitando javascript sul browser la cosa è decente?

**Comment by inrace** [comment]
Con lynks non é il massimo, ma credo possiamo sorvolare, chrome perfetto.
Il 01/lug/2015 11:03, "acavestro" <notifications@github.com> ha scritto:

**Comment by acavestro** [comment]
Non so dove sbattere la testa, non trovo indicazioni su internet su come trattare il problema..

**Comment by inrace** [comment]
Il fatto che links mostri i testi come se si avesse clickato sui bottoni
"mostra testo"  su tutte le canzoni significa che ha eseguito il codice
javascript?
Il 01/lug/2015 12:15, "acavestro" <notifications@github.com> ha scritto:

**Comment by fsestini** [comment]
Non ho avuto tempo di cercare altrove, ma su stackoverflow dicono che 
lynx non supporta javascript. Quindi in teoria non dovrebbe proprio 
eseguirlo.

**Comment by gpozzan** [comment]
No, i testi sono parte della pagina, javascript non fa altro che mostrarli
e nasconderli dinamicamente.

Probabilmente (non ricordo bene) vengono nascosti a caricamento da
javascript quindi il browser testuale li mostra.

2015-07-01 12:24 GMT+02:00 Filippo Sestini <notifications@github.com>:

**Comment by gpozzan** [comment]
Oppure è il css a nasconderli, boh, comunque fatto sta che sono lì, e
questo potrebbe essere un problema anche per gli screen reader (imo), una
soluzione che secondo me potrebbe funzionare l'avevo scritta su github
nella issue.

2015-07-01 12:29 GMT+02:00 Gabriele Pozzan <fanofthepigpen@gmail.com>:

**Comment by acavestro** [comment]
Il css li nasconde, il js li abilita.

Quindi non dovrebbe manco visualizzarli.

**Comment by gpozzan** [comment]
On 1 July 2015 at 12:36, acavestro <notifications@github.com> wrote:

> Il css li nasconde, il js li abilita.
>
> Quindi non dovrebbe manco visualizzarli.
>

Ok, quindi vuol dire che il browser non applica il css e quindi li mostra,
se non ho capito male.

Se è così bisogna sistemare e l'unica cosa che mi viene in mente è
iniettare cose da js.

**Comment by acavestro** [comment]
Viene fuori una gran porcheria se inietti il testo via js.
Proverei con uno screenreader. Se legge male, ci bestemmieremo sopra.

**Comment by gpozzan** [comment]
E che ne dici di iniettare i link invece?

Risolviamo almeno il fatto di avere dei link non funzionanti.

Rimane il problema di avere SIA i testi SIA un link a una pagina esterna
che contiene i testi, ma mi sembra meno grosso il problema.

**Comment by inrace** [comment]
Oggi pome provo uno screenreader, o un qualche sito che simuli la cosa.

Il tasto che mostra tutti i testi quando javascript é disattivato,
riusciamo a mettere che invece di mostrare tutti i titoli, e clickando su
un titolo si apre una pagina con il testo della canzone?

Così lo screen reader non deve leggere tutti gli n-1 testi

Fattibile in poco tempo?
Il 01/lug/2015 12:45, "acavestro" <notifications@github.com> ha scritto:

**Comment by fsestini** [comment]
Non sarebbe brutta come idea. D'altronde lo facciamo già per foto e
concerti.

**Comment by inrace** [comment]
Ho provato anch'io con lynx ed in effetti ci sono meno problemi rispetto a
links2.

Semplicemente perchè lynx invece di aprire una pagina e restituire l'errore
404 avvisa subito che c'è stato un errore ed evita di aprirla...

vi segnalo comunque  che entrambi hanno problemi nell'accesso alla home,
infatti entrambi si fermano al reindirizzamento e ti obbligano a refreshare
la pagina.
può darsi che sia un problemo solo mio ma ne dubito.

Il giorno 1 luglio 2015 13:23, Filippo Sestini <notifications@github.com>
ha scritto:

> Non sarebbe brutta come idea. D'altronde lo facciamo già per foto e
> concerti.
>

**Comment by fsestini** [comment]
Anche da me ha problemi con l'index

**Comment by acavestro** [comment]
Dobbiamo davvero supportare i browser testuali?

**Comment by inrace** [comment]
Nella relazione ho scritto che dai test fatti con lynx risulta che il sito
è pienamente utilizzabile, la cosa è vera visto che l'errore che da
scompare subito e permette tranquillamente di continuare a navigare.
Anche l'inserimento dei commenti funziona a pieno

2015-07-02 0:05 GMT+02:00 acavestro <notifications@github.com>:

**Comment by inrace** [comment]
btw il problema non è dovuto semplicemente al connubio noCSS-noJavascript, perchè togliendo entrambi chrome continua a funzionare senza dare errori 404.
Immagino convenga lasciare le cose così come stanno...

**Comment by acavestro** [comment]
> Immagino convenga lasciare le cose così come stanno...

Si dai, me ne sbatterei. Chiudo, se qualcuno ha bisogno riapra.
