### ISSUE TITLE
Estrarre javascript da pagina dettaglio concerti.

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#10]
Una cosa che mi son sempre dimenticato di fare, scusate.

Bisognerebbe estrarre il javascript di google maps su un file esterno, dovrebbe essere abbastanza semplice come cosa, basta capire come passargli i parametri che gli servono (latitudine, longitudine se non ricordo male).

**Comment by acavestro** [comment]
Fatto.
