### ISSUE TITLE
Sistemare elementi del navbar in browser telefono

### ISSUE THREAD

**Issue by fsestini** [tecweb-codedeck/repoosceno#16]
Gli elementi del menu vanno a capo quando il telefono è in landscape mode.

![2015_06_28_16 22 55](https://cloud.githubusercontent.com/assets/9115681/8396712/4ff7890a-1db2-11e5-80f7-eec0de5729de.png)

**Comment by acavestro** [comment]
Si, immagino. Al momento la media query è solo portrait, sto pensando se renderla anche landscape o farne una versione più *vicina* a quella di default

**Comment by acavestro** [comment]
Invece, ho deciso di adottare la strategia fottesega e risolvere impostando la media query portrait anche per il landscape.

Guardaci un po', se ti capita.

**Comment by fsestini** [comment]
Ora è ok.
