### ISSUE TITLE
Ottimizzare pagina concerti

### ISSUE THREAD

**Issue by acavestro** [tecweb-codedeck/repoosceno#17]
l'XML contiene molta più roba di quella che stampiamo.

O stampiamo di più, o togliamo info.

**Comment by acavestro** [comment]
Also, ho come l'impressione che l'XSL stampi cose che potrebbero non essere state definite in quanto non obbligatorie nell'XSD. Bisogna fare un bel check.

@fsestini, te ne puoi occupare?

**Comment by fsestini** [comment]
I tag non visualizzati sono <ora> e <indicazioni>. L'ora di inizio concerto è molto utile, e la aggiungo.
Il tag <indicazioni>, invece, è superfluo IMO. Non ha granchè senso offrire delle indicazioni nostre quando c'è google maps di fianco, che offre quello e molto altro, fruibile da app/qualsivoglia dispositivo.
Se nessuno mi ferma lo aro.

**Comment by gpozzan** [comment]
2015-06-29 19:51 GMT+02:00 Filippo Sestini <notifications@github.com>:

> I tag non visualizzati sono e . L'ora di inizio concerto è molto utile, e
> la aggiungo.
> Il tag , invece, è superfluo IMO. Non ha granchè senso offrire delle
> indicazioni nostre quando c'è google maps di fianco, che offre quello e
> molto altro, fruibile da app/qualsivoglia dispositivo.
> Se nessuno mi ferma lo aro.
>


In reltà quel tag l'ho messo solo perché xslt se trova un tag vuoto lo
chiude automaticamente, cioè ad esempio prende un <div> e lo chiude così:
<div />. Questo è un problema perché noi il div lo apriamo e chiudiamo
normalmente quindi la situazione finale è una cosa del tipo: <div ... />
</div> che invalida il codice.

Ora non so se si possano fare dei div "autochiusi" del tipo <div />, se si
può fare basta togliere dal foglio xsl il tag di chiusura e il tutto
dovrebbe sistemarsi.

Spero si sia capito, in caso contrario prova a togliere il campo e a vedere
se ti valida il codice della pagina e il problema dovrebbe apparirti X)

btw la Gaggi ha più detto niente? ci fa consegnare o no?

**Comment by acavestro** [comment]
> btw la Gaggi ha più detto niente? ci fa consegnare o no?

Sto attendendo la risposta come un cane in pena, ma temo che dovremo aspettare domani per saperlo :(

**Comment by fsestini** [comment]
> On Jun 29, 2015, at 7:57 PM, gpozzan <notifications@github.com> wrote:
> 
> Spero si sia capito, in caso contrario prova a togliere il campo e a vedere
> se ti valida il codice della pagina e il problema dovrebbe apparirti X)

Non ho capito granché, ma devo ancora guardare l’XSL e il Perl. Ci aggiorniamo quando l’avrò fatto.

— 
Filippo Sestini
sestini.filippo@gmail.com
(+39) 333 6757668

**Comment by acavestro** [comment]
Hai più guardato, @fsestini ?

**Comment by fsestini** [comment]
Ho dato una letta l'altra sera al codice Perl, ma non sono riuscito a capire per quale motivo la generazione dell'html vada a puttane togliendo quel tag.

**Comment by acavestro** [comment]
Uhm, forse ho capito male il problema, ma se tolgo il tag indicazioni dall'xml la pagina di info concerto mi viene visualizzata senza problemi..

**Comment by gpozzan** [comment]
Perché viene fatto in automatico. Se tu metti un tag vuoto ti viene chiuso
in automatico (da xslt penso).
Così:
INPUT: <tag></tag> OUTPUT: <tag/></tag> <-- non valida
INPUT: <tag>a</tag> OUTPUT: <tag>a</tag>
INPUT: <tag> OUTPUT <tag/>
INPUT: <tag> bla OUTPUT: <tag> bla <-- non valida

Sto andando a memoria ma mi pare che siano proprio questi i risultati delle
prove che avevo fatto.
Comunque basta che togli il contenuto (cioè le indicazioni stradali alla
buona che ci ho messo) e provi a vedere se ti valida l'html.

2015-07-01 15:05 GMT+02:00 Filippo Sestini <notifications@github.com>:

**Comment by gpozzan** [comment]
2015-07-01 15:10 GMT+02:00 acavestro <notifications@github.com>:

> Uhm, forse ho capito male il problema, ma se tolgo il tag indicazioni
> dall'xml la pagina di info concerto mi viene visualizzata senza problemi..
>

Ah davvero?
Che strano, ricordo bene di aver avuto questo problema.. ora non posso
riprodurlo perché non sono sul mio pc.
Hai provato anche con js disattivato?
Ti valida sempre?

**Comment by fsestini** [comment]
Non si tratta di tag vuoto. Ho proprio rimosso il tag <indicazioni> 
dall'XML e dal relativo schema.
Il Perl non dovrebbe risentire dell'assenza di un tag di cui non ha 
nemmeno conoscenza.

**Comment by gpozzan** [comment]
2015-07-01 15:14 GMT+02:00 Filippo Sestini <notifications@github.com>:

> l Perl non dovrebbe risentire dell'assenza di un tag di cui non ha
> nemmeno conoscenza.
>

Il problema a me lo dava sul div vuoto che generava l'xslt (quello dove poi
va la pagina).
In ogni caso se voi togliete le indicazioni (lasciando quindi quel div
vuoto) e l'html della pagina è strict e valida meglio :) forse aveva
qualche problema l'xslt che avevo installato quando ho visto il problema.
Provate anche con js disattivato per sicurezza e ci togliamo il pensiero.

**Comment by gpozzan** [comment]
2015-07-01 15:16 GMT+02:00 Gabriele Pozzan <fanofthepigpen@gmail.com>:

> Il problema a me lo dava sul div vuoto che generava l'xslt (quello dove
> poi va la pagina).
>

Sì banane: *quello dove va la MAPPA

**Comment by acavestro** [comment]
Ribadisco, togliendo i tag indicazioni dall'xml, la pagina viene costruita, visualizzata e validata senza problemi.

Quindi?

**Comment by gpozzan** [comment]
Anche con js disabilitato?

Se sì buono così, a parte il fatto che il mio computer è posseduto dagli
spiriti X)

2015-07-01 15:20 GMT+02:00 acavestro <notifications@github.com>:

**Comment by fsestini** [comment]
Appena riesco vedo di fare uno screen del problema che mi si propone.
Ammesso che si proponga ancora, a questo punto.

**Comment by acavestro** [comment]
Anche con js disabilitato.

Pullate le ultime modifiche (magari ho risolto involontariamente), cancellate la cache e provate.

**Comment by fsestini** [comment]
Ecco il problema di cui vi parlavo: mi mette il footer come parte di main-content, mentre dovrebbe essere sotto. Una conseguenza è che il bordo arrotondato non si vede.

![screen shot 2015-07-01 at 7 53 20 pm](https://cloud.githubusercontent.com/assets/9115681/8461162/e8ef1f54-202a-11e5-8921-b03a84b70ef1.png)

**Comment by inrace** [comment]
Il bordo arrotondato della parte gialla?

Prova ad aggiornare il repo perchè a me si vede arrotondato

2015-07-01 19:55 GMT+02:00 Filippo Sestini <notifications@github.com>:

**Comment by fsestini** [comment]
> On Jul 1, 2015, at 8:08 PM, inrace <notifications@github.com> wrote:
> 
> Il bordo arrotondato della parte gialla?
> 
> Prova ad aggiornare il repo perchè a me si vede arrotondato

Niente da fare, nemmeno su un checkout fresco.
A sto punto avrò il Perl rotto.

**Comment by acavestro** [comment]
Corretto in f078ab2, bellezze. :wine_glass:

**Comment by inrace** [comment]
A me lo dava così anche prima del cambiamento, non è giusto in questo
screen?

2015-07-01 20:14 GMT+02:00 acavestro <notifications@github.com>:

**Comment by fsestini** [comment]
Adesso ragioniamo!

**Comment by acavestro** [comment]
Momento: non doveva esserci l'ora, da qualche parte?

(mi sono dimenticato di togliere info:indicazioni dall'XSD)

**Comment by fsestini** [comment]
Hai ragione, mi sono fatto prendere dall'emozione :P

**Comment by fsestini** [comment]
Date un occhio a:
5ed3d12a7b39ac9c8dfb3e50e96feb259ca1748d

**Comment by acavestro** [comment]
Può andare :)

**Comment by gpozzan** [comment]
comunque a me non valida ancora la pagina, non so se sia un problema del mio browser o che. Comunque il codice che mi dice firefox a fine pagina è questo:

     *<div class="clear" />*
      <div id="footer-validation">
        <img alt="sito contenente CSS valido"
             src="http://jigsaw.w3.org/css-validator/images/vcss-blue" />
        <img alt="sito contenente XHTML valido"
             src="http://www.multimediacampus.it/images/valid-xhtml.gif" />
      </div>
    </div>
</body>
</html>

**Comment by inrace** [comment]
a me la pagina concerti la valida

Il giorno 2 luglio 2015 22:12, gpozzan <notifications@github.com> ha
scritto:

**Comment by gpozzan** [comment]
Sì è stato un errore mio in realtà valida.

2015-07-02 22:25 GMT+02:00 inrace <notifications@github.com>:
