### ISSUE TITLE
Path dell'home page

### ISSUE THREAD

**Issue by acavestro** [tecweb-codedeck/repoosceno#18]
Temo che la Gaggi ci rompa un po' i coglioni se la teniamo così. E non avrebbe neanche tutti i torti. 
Proporrei:

* rinominare home.cgi in index.cgi
* modificare la navbar affinché punti a index.cgi e non a index.html
* modificare il redirect di index.html tirando via il layout e lasciando solo una scritta "Accesso al sito in corso..." (un po' come Gmail quando fai login).

L'ultima soprattutto temo che possa causarci problemi, perché l'utente potrebbe rimanere disorientato dal caricamento del sito vuoto e poi il successivo redirect (potrebbero esserci anche problemi di SEO, però in questo caso non c'interessa).

**Comment by gpozzan** [comment]
Ci stanno tutte le modifiche che dici. Se su index.html vuoi anche
sbatterci una gif di caricamento fai pure ^^

2015-06-30 10:04 GMT+02:00 acavestro <notifications@github.com>:

**Comment by fsestini** [comment]
C'è un motivo per cui non possiamo dire al server di puntare direttamente a index.cgi?

**Comment by acavestro** [comment]
Non so se sul server siano abilitati gli htaccess, in questo caso sì, si può fare.
O meglio, si può fare il redirect senza bisogno di caricare index.html.
Indago.

Terrei comunque il redirect di index.html, per sicurezza.

**Comment by acavestro** [comment]
htaccess non sembra funzionare.

**Comment by acavestro** [comment]
Fatto.
