### ISSUE TITLE
Link Webmaster nel footer?

### ISSUE THREAD

**Issue by acavestro** [tecweb-codedeck/repoosceno#19]
Credo basti contatti.

**Comment by fsestini** [comment]
Era per riempirlo un po' :P 
Comunque sì, basta il contatto della band

**Comment by acavestro** [comment]
Comunque, credo potremo riciclare il link per la sitemap (la facciamo? Apro issue)

**Comment by acavestro** [comment]
Lo usiamo per la sitemap e morta lì.
