### ISSUE TITLE
Spostare form commenti nella pagina di dettaglio delle foto.

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#2]
La Gaggi vuole il form dei commenti e i commenti visibili senza scrollare.
Una soluzione per le nostre pagine di dettaglio delle foto sarebbe spostare il form a destra della foto e mettere i commenti sotto.

Bisogna capire come impostare poi la lista dei commenti, se renderla scrollabile oppure se mostrarla semplicemente come un listone che parte a destra della foto e poi wrappa normalmente riempendo lo spazio disponibile una volta superato il bordo inferiore (oppure rimane sulla colonna di destra).

**Comment by acavestro** [comment]
L'ho fatto, prova a vedere che ne pensi. La lista dei commenti l'ho resa scrollabile.

**Comment by acavestro** [comment]
ping

**Comment by gpozzan** [comment]
Ah scusa pensavo di averti già risposto :) Così mi par buono, è above the
fold o come cazzo si dice e rende la pagina più compatta e ordinata.

**Comment by acavestro** [comment]
Ottimo, caso chiuso :)
