### ISSUE TITLE
Sitemap?

### ISSUE THREAD

**Issue by acavestro** [tecweb-codedeck/repoosceno#21]
La facciamo?

**Comment by gpozzan** [comment]
Buona idea farla i think.

**Comment by fsestini** [comment]
Approvo. E' utile, e si tira su in O(1).

**Comment by acavestro** [comment]
Domanda: servono anche i link di tutti i concerti e tutte le foto?

**Comment by gpozzan** [comment]
Non saprei, vista la loro natura incrementale potrebbe essere un po' un
casino aggiungerli tutti, a pensarci per i concerti mi sembra ancora
fattibile come cosa, per le foto un po' più complicato.

**Comment by acavestro** [comment]
Ho aggiunto una bozza.

Ho generato solo i link dei concerti, non quelli delle foto.

Ditemi che ne pensate.
