### ISSUE TITLE
Ma i commenti alle foto non dovrebbero essere *per foto*?

### ISSUE THREAD

**Issue by acavestro** [tecweb-codedeck/repoosceno#22]
Perché ogni foto carica gli stessi commenti?

**Comment by gpozzan** [comment]
Ops, forse c'è un problema con il caricamento ecc. strano, quando avevo
cambiato le cose avevo controllato, adesso do un occhio.

2015-06-30 21:41 GMT+02:00 acavestro <notifications@github.com>:

**Comment by inrace** [comment]
non è la stessa cosa che avevo chiesto io nella mail? xD

Il giorno 30 giugno 2015 21:47, gpozzan <notifications@github.com> ha
scritto:

**Comment by gpozzan** [comment]
Anzi no, non sono stato io, qualcuno ha messo le mani all'xsl che c'era per
le foto e ha tolto il controllo dell'id delle foto.
A guardare il blame mi sa che sei stato tu Antonio.

L'xslt viene chiamato con dei parametri, uno di questi è l'id della foto e
serve proprio per mostrare le foto giuste.

2015-06-30 21:47 GMT+02:00 Gabriele Pozzan <fanofthepigpen@gmail.com>:

**Comment by gpozzan** [comment]
Nello specifico il tag <xsl:param /> si prende i parametri, nell'ordine in
cui vengono passati alla funzione applyXSLParam.

2015-06-30 21:53 GMT+02:00 Gabriele Pozzan <fanofthepigpen@gmail.com>:

**Comment by acavestro** [comment]
Oooops :((((

**Comment by gpozzan** [comment]
On 30 June 2015 at 21:57, acavestro <notifications@github.com> wrote:

> Oooops :((((



Vai tranquillo, prova a correggere che non dovrebbe essere troppo difficile
:)
Già che ci metti le mani controlla anche una cosa: temo che i commenti
lasciati lo stesso giorno vengano messi nell'ordine sbagliato perché ci si
tira giù una data invece che un timestamp non so se avete già sistemato
questa cosa comunque sarebbe conveniente metterci le mani penso!

**Comment by acavestro** [comment]
A occhio e croce basta modificare xsl:sort in 
    <xsl:sort select="translate(po:data, '-', '')" order="descending"/>

**Comment by acavestro** [comment]
Okay, risolto.
