### ISSUE TITLE
Canzoni

### ISSUE THREAD

**Issue by inrace** [tecweb-codedeck/repoosceno#23]
Mettiamo gli mp3 delle canzoni?
Non possiamo metterli con sundcloud perchè serve iframe però potremmo metterli con html5, che dite?

Mi servono le canzoni in formato mp3 però, le scaricherei direttamente da soundcloud, ma li ce ne sono solo 3.

**Comment by gpozzan** [comment]
Se vuoi scarica da soundcloud, ho chiesto a quelli del gruppo e mi han
detto che preferiscono dar via solo quelle perché il cd lo danno via ai
concerti.

2015-06-30 22:34 GMT+02:00 inrace <notifications@github.com>:

**Comment by acavestro** [comment]
Meh, non sono tanto convinto.
Non vorrei che alla consegna mi dicesse "guarda che stai occupando troppo spazio".

Boh, fai tu :)

**Comment by gpozzan** [comment]
Mi pare che il limite per la consegna sia 20 mega, andate a vedere sul
solito sito di merda della Gaggi che in teoria sta scritto tutto :)

2015-06-30 22:41 GMT+02:00 acavestro <notifications@github.com>:

**Comment by inrace** [comment]
A questo punto abbiamo una buona scusa per non metterle....
Così evitiamo di aggiungere roba in html5 che poi.... compatibilità e cazzi
e mazzi....

Secondo me in home ci starebbero bene 2 link: uno a soundcloud ed uno alla
pagina facebook se avete voglia di aggiungerli

Il giorno 30 giugno 2015 22:41, acavestro <notifications@github.com> ha
scritto:

**Comment by acavestro** [comment]
Mi stavo chiedendo se mettere i link solo in home o nel footer in tutte le pagine

**Comment by inrace** [comment]
mmh bha...mettili un po' dove vuoi a mio avviso...se secondo te la home è
troppo piena mettili nel footer, e vicerversa...

2015-07-01 14:16 GMT+02:00 acavestro <notifications@github.com>:

**Comment by acavestro** [comment]
Ho aggiunto i link. Non ho messo i loghi dei social perché altrimenti hanno bordo bianco e sono un po' bruttini. 

Mi stavo chiedendo se metterli sopra alla descrizione delle pagine Storia, Album, ecc.. o addirittura togliere quest'ultimi..
