### ISSUE TITLE
ie6

### ISSUE THREAD

**Issue by inrace** [tecweb-codedeck/repoosceno#24]
lo so che non è proprio una issue, ma non sapevo dove mandarvi lo screen

![ie6](https://cloud.githubusercontent.com/assets/9109447/8441716/4f4da380-1f7a-11e5-9409-c7dffd57ae34.jpg)

Come vedete con ie6 il sito fa cagare, ma non credo ci siano da far drammi, se usi ie6 meriti di vedere male i siti

**Comment by fsestini** [comment]
> On Jun 30, 2015, at 10:51 PM, inrace <notifications@github.com> wrote:
> 
> se usi ie6 meriti di vedere male i siti

Non potrei essere più d’accordo.

— 
Filippo Sestini
sestini.filippo@gmail.com
(+39) 333 6757668

**Comment by acavestro** [comment]
Mi sembra un buon livello di usabilità, lol.

Comunque mi hanno detto che la compatibilità è IE7+, se non ricordo male.
