### ISSUE TITLE
server dove caricare il sito

### ISSUE THREAD

**Issue by inrace** [tecweb-codedeck/repoosceno#26]
Per alcuni test mi serve un link accessibile senza tunnel dove poter visitare il sito, dove lo carichiamo?

**Comment by acavestro** [comment]
Ci sto lavorando.

**Comment by acavestro** [comment]
Niente da fare, dalla rete del dipartimento non ci riesco. Ci riprovo stasera.

**Comment by acavestro** [comment]
Fai i test su questa pagina, intanto.

http://www.proposteoscene.host-ed.me/history.html

Le parti Perl/CGI danno errore 500, quando capirò perché potrebbe essere troppo tardi..

**Comment by gpozzan** [comment]
Che ci siano problemi con la configurazione del server?
Io ho dovuto smanettare per far funzionare cgi sul mio pc.

**Comment by acavestro** [comment]
Probabilmente, ma non avendo accesso ai log di quel server e avendo log
osceni sul mio, non mi resta più molto da provare..

Il giorno 1 luglio 2015 18:14, gpozzan <notifications@github.com> ha
scritto:

> Che ci siano problemi con la configurazione del server?
> Io ho dovuto smanettare per far funzionare cgi sul mio pc.
>
> On 1 July 2015 at 18:12, acavestro <notifications@github.com> wrote:
>
> > Fai i test su questa pagina, intanto.
> >
> > http://www.proposteoscene.host-ed.me/history.html
> >
> > Le parti Perl/CGI danno errore 500, quando capirò perché potrebbe essere
> > troppo tardi..
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/tecweb-codedeck/repoosceno/issues/26#issuecomment-117732456
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tecweb-codedeck/repoosceno/issues/26#issuecomment-117733676>
> .
>



-- 
Antonio Cavestro
antonio.cavestro@gmail.com
+39 3467868675

**Comment by gpozzan** [comment]
Uhm va bè, in definitiva comunque l'importante è che tutto giri sui server
della scuola X)

2015-07-01 18:22 GMT+02:00 acavestro <notifications@github.com>:

> Probabilmente, ma non avendo accesso ai log di quel server e avendo log
> osceni sul mio, non mi resta più molto da provare..
>
> Il giorno 1 luglio 2015 18:14, gpozzan <notifications@github.com> ha
> scritto:
>
> > Che ci siano problemi con la configurazione del server?
> > Io ho dovuto smanettare per far funzionare cgi sul mio pc.
> >

**Comment by inrace** [comment]
@gpozzan per fare un test che ti dice se il sito è conforme agli standard A
o AA o AAA servirebbe un link da dare in pasto al sito che fa i controlli.

Il gruppo di sebastiano ha usato github? è a pagamento quella roba?

Il giorno 1 luglio 2015 18:25, gpozzan <notifications@github.com> ha
scritto:

> Uhm va bè, in definitiva comunque l'importante è che tutto giri sui server
> della scuola X)
>
>
> 2015-07-01 18:22 GMT+02:00 acavestro <notifications@github.com>:
>
> > Probabilmente, ma non avendo accesso ai log di quel server e avendo log
> > osceni sul mio, non mi resta più molto da provare..
> >
> > Il giorno 1 luglio 2015 18:14, gpozzan <notifications@github.com> ha
> > scritto:
> >
> > > Che ci siano problemi con la configurazione del server?
> > > Io ho dovuto smanettare per far funzionare cgi sul mio pc.
> > >

**Comment by gpozzan** [comment]
Non lo so (ma immagino non sia a pagamento perché il sito è ancora su),
comunque anche a loro non andava cgi su github.

2015-07-01 18:34 GMT+02:00 inrace <notifications@github.com>:

> @gpozzan per fare un test che ti dice se il sito è conforme agli standard A
> o AA o AAA servirebbe un link da dare in pasto al sito che fa i controlli.
>
> Il gruppo di sebastiano ha usato github? è a pagamento quella roba?
>
> Il giorno 1 luglio 2015 18:25, gpozzan <notifications@github.com> ha
> scritto:
>
> > Uhm va bè, in definitiva comunque l'importante è che tutto giri sui
> server
> > della scuola X)
> >
> >
> > 2015-07-01 18:22 GMT+02:00 acavestro <notifications@github.com>:
> >
> > > Probabilmente, ma non avendo accesso ai log di quel server e avendo log
> > > osceni sul mio, non mi resta più molto da provare..
> > >
> > > Il giorno 1 luglio 2015 18:14, gpozzan <notifications@github.com> ha
> > > scritto:
> > >
> > > > Che ci siano problemi con la configurazione del server?
> > > > Io ho dovuto smanettare per far funzionare cgi sul mio pc.
> > > >

**Comment by inrace** [comment]
e come generano le pagine?

Il giorno 1 luglio 2015 18:36, gpozzan <notifications@github.com> ha
scritto:

**Comment by gpozzan** [comment]
Hanno pochissimo cgi loro, come la maggior parte dei gruppi che fanno
questo progetto mi sa.
Tutto html e cgi usato solo per news, commenti ecc.

2015-07-01 18:39 GMT+02:00 inrace <notifications@github.com>:

**Comment by acavestro** [comment]
Dagli il link della history, te l'ho passato.

-- 
Antonio Cavestro
antonio.cavestro@gmail.com
+39 3467868675
Il 01/lug/2015 18:36, "gpozzan" <notifications@github.com> ha scritto:

**Comment by inrace** [comment]
vabbè in ogni caso il sito che fa il controllo non mi da nememno la
certificazione AA sulla pagina storia perchè dice che il contrasto dei
colori non va bene...

ergo quel sito non lo usiamo per i test xD

La certificazione AAA se non ho capito male non ce l'ha da sempre per il
contrasto e perchè servirebbe una pagina "help" che aiuti gli utenti con
difficoltà

Criterion 3.3.5 [Help]
The intent of this Success Criterion is to help users avoid making
mistakes. Some users with disabilities may be more likely to make mistakes
than users without disabilities. Using context-sensitive help, users find
out how to perform an operation without losing track of what they are doing

The objective of this technique is to provide context sensitive help for
users as they enter data in forms by providing at least one link to the
help information on each Web page. The link targets a help page with
information specific to that Web page. Another approach is to provide a
help link for every interactive control. Positioning this link immediately
before or after the control allows users to easily tab to it if they have
problems in the control. Displaying the help information in a new browser
window ensures that any data that has already been entered into the form
will not be lost. NOTE: A link is not the only means to provide help.

Il giorno 1 luglio 2015 18:39, Mattia Buso <mattia.buso@gmail.com> ha
scritto:

**Comment by inrace** [comment]
http://www.cynthiasays.com/ShowInstances.aspx?resultId=5190769

The objective of this technique is to make sure that users can read text
that is presented over a background. This technique relaxes the 5:1
contrast ratio requirement for text that is at least 18 point (if not bold)
or at least 14 point (if bold).

http://www.w3.org/TR/WCAG20-TECHS/G18.html

2015-07-01 18:42 GMT+02:00 Mattia Buso <mattia.buso@gmail.com>:

**Comment by acavestro** [comment]
Qui mi dice che è tutto perfetto:
http://contrastchecker.com/?swatch_session=oxe4Ms1gBBPz

Provane un altro, vediamo la terza opinione.

**Comment by acavestro** [comment]
Anche qui tutto okay
http://webaim.org/resources/contrastchecker/

Background: #FFE80D
Foreground: #000000

**Comment by inrace** [comment]
Vi mando degli screen di cosa questo sito segni come errore, magari vi
viene l'illuminazione...sennò non lo mettimo tra i test fatti e per il
contrasto dei colori usiamo uno dei siti di Antonio

2015-07-01 19:13 GMT+02:00 acavestro <notifications@github.com>:

**Comment by inrace** [comment]
Il giorno 1 luglio 2015 20:58, Mattia Buso <mattia.buso@gmail.com> ha
scritto:

**Comment by acavestro** [comment]
Non credo che gli allegati alle email non arrivano, li devi mettere nel ticket su github..

**Comment by inrace** [comment]
sorry pensavo leggeste anche voi dalle mail

![contrasto colori](https://cloud.githubusercontent.com/assets/9109447/8466526/0ebbacce-2054-11e5-94e9-ac98572ee130.jpg)

![contrasto colori2](https://cloud.githubusercontent.com/assets/9109447/8466531/15937414-2054-11e5-8058-0a198369fac6.jpg)

![contrasto colori3](https://cloud.githubusercontent.com/assets/9109447/8466541/1e0c2d3e-2054-11e5-8345-1bc7b9d0c6ac.jpg)

In ogni caso ho fatto il test con altri siti e va tutto bene, quindi non mi preoccuperei più di questa storia dei colori

**Comment by fsestini** [comment]
Uhm, non sto capendo. Come fa una scritta bianca su sfondo nero a non 
avere abbastanza contrasto lol

**Comment by acavestro** [comment]
> sorry pensavo leggeste anche voi dalle mail

Credo che se non li carichi qui su github non si ricevano neanche per mail..

> Uhm, non sto capendo. Come fa una scritta bianca su sfondo nero a non
avere abbastanza contrasto lol

Me lo sto chiedendo anch'io, lol
