### ISSUE TITLE
problemi di visualizzazione

### ISSUE THREAD

**Issue by inrace** [tecweb-codedeck/repoosceno#27]
![vis1](https://cloud.githubusercontent.com/assets/9109447/8459620/d0d4a436-201e-11e5-8a70-44c6c05d6b38.jpg)

se la finestra è stretta il form dei commenti invade la fascia nera

![vis2](https://cloud.githubusercontent.com/assets/9109447/8459631/dfec6594-201e-11e5-84e2-239b9599b607.jpg)

Vi avevo già parlato di questo problema, se los chermo è grande la pagina si presenta così

Ce ne sbattiamo?

**Comment by acavestro** [comment]
Risolto per il guestbook.
La pagina dei concerti io la vedo senza problemi se restringo la finestra.
Riprova, magari è cambiato qualcosa e si è risolto.
Altrimenti: che browser usi?

**Comment by inrace** [comment]
Il problema della pagina concerti c'è quando si allarga la finestra, nel 17" è perfetta, nel 24 è come vedi in foto

**Comment by acavestro** [comment]
Ho capito, ma ho bisogno dell'Inspector aperto su quel browser per trovare la soluzione. Non avendolo, non posso risolvere.

**Comment by acavestro** [comment]
(prova a trovarne una te)

**Comment by inrace** [comment]
ahn ok, ora provo

**Comment by acavestro** [comment]
Ce ne sbattiamo.
