### ISSUE TITLE
validazione

### ISSUE THREAD

**Issue by inrace** [tecweb-codedeck/repoosceno#28]
la pagina history non viene validata perchè usiamo <footer> che è stato introdotto con html5, è un problema??

**Comment by acavestro** [comment]
Certo che è un problema, correggo.

**Comment by acavestro** [comment]
Corretto, ora lo supera.

Comunque, la validazione sulle altre pagine falla pure copia-incollando il codice renderizzato dal browser sul tester del W3C.. :)

**Comment by inrace** [comment]
Grande! Ma html5 non era tipo diventato standard?

In ogni caso css valida tutto.

"Comunque, la validazione sulle altre pagine falla pure copia-incollando il
codice renderizzato dal browser sul tester del W3C.. :)"

cioè, apro la pagina dal browser faccio un ctrl+u e valido quello? e nella
relazione gli dico che abbiamo fatto così?

Il giorno 1 luglio 2015 19:19, acavestro <notifications@github.com> ha
scritto:

**Comment by acavestro** [comment]
> Grande! Ma html5 non era tipo diventato standard?

Si, ma noi stiamo usando XHTML 1.0 Strict (Guarda il nostro Doctype), non possiamo mischiare più tipi di HTML nella stessa pagina, lol.

> In ogni caso css valida tutto.

Hai provato anche i css small, text e print?
(il .css, non il .scss, mi raccomando)

> cioè, apro la pagina dal browser faccio un ctrl+u e valido quello? e nella
relazione gli dico che abbiamo fatto così?

Beh, se tu dai l'indirizzo della pagina al W3C lui fa la stessa cosa :D

**Comment by inrace** [comment]
Il giorno 1 luglio 2015 19:30, acavestro <notifications@github.com> ha
scritto:

> Si, ma noi stiamo usando XHTML 1.0 Strict (Guarda il nostro Doctype), non
> possiamo mischiare più tipi di HTML nella stessa pagina, lol.



mmmh...ha parecchio senso....

      Hai provato anche i css small, text e print?
      (il .css, non il .scss, mi raccomando)

Certo, ho provato tutti i css, van tutti bene!


      Beh, se tu dai l'indirizzo della pagina al W3C lui fa la stessa cosa
:D

Che URL gli do se non ho un server che faccia girare lo script?

**Comment by acavestro** [comment]
> Che URL gli do se non ho un server che faccia girare lo script?

Dagli il codice, è la stessa cosa, lol!

**Comment by inrace** [comment]
Ti ho detto gli do il codice tu mi hai risposto, puoi darli l'indirizzo e
si arrangia, ti chiedo che indirizzo e mi dici di dargli il codice!!!!!!!!!!

btw non chiudere sta issue che potrebbe servirmi il tuo aiuto per alcuni
problemi di validazione xD

Il giorno 1 luglio 2015 19:42, acavestro <notifications@github.com> ha
scritto:

**Comment by inrace** [comment]
La pagina Album il <div id="gallery-album"> viene assegnato uguale
per tutte le foto.

(Se ne occuperà Antonio appena ha tempo)

Il giorno 1 luglio 2015 19:45, Mattia Buso <mattia.buso@gmail.com> ha
scritto:

**Comment by inrace** [comment]
scusa pagina GALLERY** non  ALBUM

Il giorno 1 luglio 2015 20:05, Mattia Buso <mattia.buso@gmail.com> ha
scritto:

**Comment by acavestro** [comment]
Corretto :)

**Comment by inrace** [comment]
Ottimo
