### ISSUE TITLE
Validazione guestbook

### ISSUE THREAD

**Issue by inrace** [tecweb-codedeck/repoosceno#29]
i commenti vanno messi dentro ad un tag <p> <p /> o cose simili, non possono essere messi come codice libero nel body

**Comment by acavestro** [comment]
Prova ora.

**Comment by inrace** [comment]
Ottimo funziona, dovete ancora metterci mano sul guestbook?

**Comment by acavestro** [comment]
Probabilmente metteremo un paio di pulsantini in modo da inserire via javascript il grassetto e il corsivo.

**Comment by gpozzan** [comment]
bravissimi, poi copiate tutto anche su photo_page (scusate se mi ripeto ma
lo faccio solo per sicurezza :D )

**Comment by acavestro** [comment]
Il form è lo stesso, lo genera library.pm

Volendo si può anche fare la funzione che aggiunge i commenti al guestbook, così la scriviamo una volta sola ( @fsestini )

**Comment by acavestro** [comment]
Come siamo presi qui?

(Andrebbero fatti dei pulsanti JS per formattare il testo, altrimenti la funzionalità non serve)
(A sto punto quasi quasi toglierei, lol)

Piuttosto, controlliamo che nome e testo non siano vuoti, prima di inserire?

**Comment by acavestro** [comment]
Sto ticket chiudiamolo, la validazione è risolta.
