### ISSUE TITLE
screen reader

### ISSUE THREAD

**Issue by inrace** [tecweb-codedeck/repoosceno#30]
Premetto che fare i  test con gli screen reader è una cosa strana e mi trovo in difficoltà ad ambientarmi

Penso comunque che i link "Vedi tutti" e "Vedi tutte" non sarebbero comprensibili per un non vedente, credo andrebbero cambiate con "vedi tutti i concerti" oppure "vedi la lista completa dei concerti" insomma una cosa più specifica, che ne pensate?

**Comment by inrace** [comment]
![link_home](https://cloud.githubusercontent.com/assets/9109447/8463391/3bbcabf2-203a-11e5-9ac5-39f735022a50.jpg)

questi sono i link come li vede lo screen reader, a mio parere anche "Dettagli"  andrebbe cambiato con qualcosa di più specifico.

a mio parere è una cosa importante, seocndo voi?

**Comment by inrace** [comment]
La pagina concerti legge le immaigni con la data in inglese " twenty-five luglio two thousand fifteen"
e anche: Montecchio Maggiore (VI) lo legge "Montecchio Maggiore left paren VI right paren"

**Comment by inrace** [comment]
Comincio a credere che la lettura in inglese sia dovuta ad un'impostazione dello screen reader, non credo si possa forzare il modo in cui vengono letti i numeri tramite <span lang="it", ma potrei sbagliarmi.
Qualcuno ha conferme o confutazioni?

**Comment by gpozzan** [comment]
2015-07-02 1:22 GMT+02:00 inrace <notifications@github.com>:

> Comincio a credere che la lettura in inglese sia dovuta ad un'impostazione
> dello screen reader, non credo si possa forzare il modo in cui vengono
> letti i numeri tramite <span lang="it", ma potrei sbagliarmi.
> Qualcuno ha conferme o confutazioni?
>


Sì quello dipende dalla lingua dello screen reader, non mi preoccuperei
troppo.

Piuttosto mi è venuto in mente che un link "Vedi tutte" messo apposta per
dei ciechi potrebbe non essere la cosa più "di tatto" della storia. Che ci
sia una frase migliore da usare?

**Comment by inrace** [comment]
Da questo punto di vista non lo so, in ogni caso i nomi deve essere più
precisi. Messi li così sono difficili da usare
Il 02/lug/2015 08:05, "gpozzan" <notifications@github.com> ha scritto:

**Comment by acavestro** [comment]
>Da questo punto di vista non lo so, in ogni caso i nomi deve essere più
precisi. Messi li così sono difficili da usare

Prova ora.

**Comment by inrace** [comment]
la pagina concerti ha lo stesso problema, i link si chiamano tutti "vedi dettagli", meglio cambiarli con qualcosa di più specifico

(se ne sta occupando @acavestro)

**Comment by acavestro** [comment]
Fatto.
Però non ti ho cambiato il link in home page perché non ci sarebbe spazio..

**Comment by inrace** [comment]
In home c'è solo un concerto quindi non è un problema a mio avviso

**Comment by acavestro** [comment]
Ottimo allora :+1:

**Comment by acavestro** [comment]
Ho fatto una modifica perché altrimenti da mobile avevo problemi. Come li vedi ora da screen reader?

**Comment by inrace** [comment]
![link_pag_conc2](https://cloud.githubusercontent.com/assets/9109447/8480461/115f7886-20de-11e5-91b4-f40df52d9762.jpg)

Perfetto.

ho controllato anche da browser testuale e va benone.

**Comment by acavestro** [comment]
Okay :+1: 

Sostanzialmente ho tolto il nome del posto e la data da browser normali e da cellulari, perché in quest'ultimi si vedeva male.

**Comment by acavestro** [comment]
Chiudo per fare ordine, se ci sono altri problemi apri altri ticket.
