### ISSUE TITLE
tabindex

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#31]
Apro per sicurezza, al massimo chiudete pure tutto.
Ci sono tutti i tabindex dove andrebbero messi?

**Comment by acavestro** [comment]
Io non li ho mai messi :laughing:

**Comment by gpozzan** [comment]
Ti dirò, allo stato attuale il tab segue l'ordine di apparizione dei link, il che non mi sembra male, cioè, è come l'avrei fatto io coi tabindex. Quindi direi bene così, magari @inrace  scrivilo nella tua parte di accessibilità che a noi va bene che il sito sia visualizzato così e per questo non abbiamo messo i tabindex.

**Comment by inrace** [comment]
Done

**Comment by gpozzan** [comment]
Testali anche va, che nelle pagine iniettiamo link da dieci posti diversi e
qualcuno può sfuggire.

**Comment by inrace** [comment]
In che senso testali? Ho messo nella relazione che non li abbiamo usati perchè l'ordine di tabulazione ci andava già bene. Ho controllato già le pagine ed in effetti mi sembra sensato come ordine. Prima passa la Navbar poi scende da sx a dx fino al footer

**Comment by gpozzan** [comment]
ah ok perfetto avevo capito male io, bene così ;)

2015-07-03 9:58 GMT+02:00 inrace <notifications@github.com>:
