### ISSUE TITLE
problemi visualizzazione titolo Social Network in Home Page

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#34]
Sul mio firefox su ubuntu si vede sballato quando la finestra è troppo grande purtroppo, non so se è risolvibile facilmente.

Also occhio perché social network ecc non hanno gli span xml:lang, adesso li metto.

![socialproblem](https://cloud.githubusercontent.com/assets/9366409/8486860/3009c7f8-2108-11e5-909f-92283b9c2f65.png)

**Comment by inrace** [comment]
anche la pagina concerti ha problemi se si allarga la finestra

Il giorno 2 luglio 2015 22:18, gpozzan <notifications@github.com> ha
scritto:

**Comment by acavestro** [comment]
Il problema in home l'ho risolto.
La pagina concerti io la vedo bene e se non riesco a replicare il problema non so come risolvere..

**Comment by inrace** [comment]
A me da ancora il problema in home.
quando si stringe la finestra la scritta social network va a puttane, se non riesci a risolvere al volo a mio parere potresti anche togliere i link

**Comment by acavestro** [comment]
A me ora va. Prova, altrimenti tolgo.

**Comment by acavestro** [comment]
Ci siamo rotti, lo togliamo.
