### ISSUE TITLE
Non mi valida la home.

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#35]
Il buon vecchio https://validator.w3.org/#validate_by_input mi da problemi:

 Line 68, Column 70: there is no attribute "target"
…w.facebook.com/ProposteOscene" target="_blank"><span xml:lang="en">Facebook</s…

Line 78, Column 12: document type does not allow element "h2" here; missing one of "object", "ins", "del", "map", "button" start-tag
    <dt><h2>Prossimo Concerto</h2></dt>

 Line 84, Column 14: document type does not allow element "h2" here; missing one of "object", "ins", "del", "map", "button" start-tag
      <dt><h2>Foto casuale</h2></dt>

@acavestro  con un po' di css si riesce a risolvere la questione del fatto che non si possono inserire h2 dentro i <dt>? (a livello grafico intendo?)

Per quanto riguarda quell'attributo target? A chi l'ha messo validava la pagina?

**Comment by inrace** [comment]
Per il primo errore basta togliere    target="_blank"   così apre la pagina
facebook e quella soundcloud senza aprire una nuova finestra e apposto così.

Gli altri 2 errori non li ho ben capiti

**Comment by gpozzan** [comment]
Gli altri due errori vogliono dire che non si possono usare i tag <h2> e
affini all'interno di un <dt>, tutto qua, basta pastrocciare col css per
mantenere l'effetto grafico suppongo.

In ogni caso aprire una nuova finestra non è quasi mai una buona idea per
motivi di usabilità, quindi lo toglierei a prescindere.

In ultimo caso: bisogna validare le pagine quando si tocca l'html!

2015-07-02 22:49 GMT+02:00 inrace <notifications@github.com>:

**Comment by inrace** [comment]
immagino sia meglio se lo tocca antonio il CSS.

Il giorno 2 luglio 2015 22:51, gpozzan <notifications@github.com> ha
scritto:

**Comment by acavestro** [comment]
Ora valida.
