### ISSUE TITLE
Controllare che ci siano tutti gli xml:lang

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#36]
@inrace parte dell'accessibilità è anche avere tutti gli xml:lang impostati su TUTTE le parole di origine straniera, sto facendo un giro per il sito e ne ho trovati un po' che mancano. Adesso li aggiungo, domani mattina magari fatti un giro anche tu e controlla che ci siano tutti. Su queste cose la Gaggi si incazza.

**Comment by inrace** [comment]
Ok

Il giorno 2 luglio 2015 22:28, gpozzan <notifications@github.com> ha
scritto:
