### ISSUE TITLE
Differenziare i link-bottoni già visitati da quelli da visitare.

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#5]
Un semplice elemento di usabilità che è in genere apprezzato (e credo piaccia alla Gaggi), bisogna in qualche modo evidenziare ciò che è già stato cliccato da ciò che non lo è stato (vale anche per le foto i believe).

**Comment by fsestini** [comment]
Che veste grafica abbiamo deciso/decidiamo?

**Comment by acavestro** [comment]
Proverei a fare lo sfondo dei link leggermente più grigio, che ne dici?

**Comment by fsestini** [comment]
Riesci a fare uno screen di esempio? Non vorrei che il grigio lo facesse sembrare un bottone "disabilitato".

**Comment by acavestro** [comment]
Idea:
![schermata 2015-07-01 alle 11 23 41](https://cloud.githubusercontent.com/assets/6882005/8451458/ba49afee-1fe3-11e5-9afa-9b1c6778e6e0.png)

Problema: non vale per le immagini cliccabili.

**Comment by fsestini** [comment]
On 07/01/2015 11:24 AM, acavestro wrote:
>
> Idea:
> schermata 2015-07-01 alle 11 23 41 
> <https://cloud.githubusercontent.com/assets/6882005/8451458/ba49afee-1fe3-11e5-9afa-9b1c6778e6e0.png>
>
> Problema: non vale per le immagini cliccabili.
>


Per funzionare, funziona. E' che stona un po' con il resto del color scheme.

**Comment by acavestro** [comment]
Già. È che bisogna pure vedere che il contrasto sia buono (non ho ancora provato con il purple).

Non so, non mi vengono molte idee. Voi? @gpozzan @inrace

**Comment by gpozzan** [comment]
On 1 July 2015 at 11:44, acavestro <notifications@github.com> wrote:

> Già. È che bisogna pure vedere che il contrasto sia buono (non ho ancora
> provato con il purple).
>
>
Direi che ci può stare se gli strumenti di valutazione dei contrasti ci
danno il "vai Denis".

**Comment by acavestro** [comment]
![schermata 2015-07-01 alle 12 14 15](https://cloud.githubusercontent.com/assets/6882005/8452359/b63ba4f0-1fea-11e5-9dbb-717c7de29899.png)


E per i link con immagini?

**Comment by gpozzan** [comment]
Non si riesce a sfumarle con un altro colore a livello "programmatico"?

**Comment by acavestro** [comment]
Si può ma 

1) bisogna studiare la cosa
2) non due giorni prima della consegna

**Comment by gpozzan** [comment]
Aggiungere un bordino statico di colore diverso da quello che si vede
quando ci si passa sopra col mouse?

**Comment by acavestro** [comment]
Ora come ora le foto hanno già bordo nero. Potremmo farlo viola.

**Comment by gpozzan** [comment]
On 1 July 2015 at 12:22, acavestro <notifications@github.com> wrote:

> Potremmo farlo viola.


Yup, sempre stando sul color safe secondo me potrebbe andare bene e se non
altro mostra che ci abbiamo pensato e provato :)

**Comment by fsestini** [comment]
Ma non possiamo scegliere due colori, A e B, e contornare le immagini con
* A se clickabile
* B se già visitata
* nulla se non cliccabili
?

Per rimanere coerenti con i link testuali, potremmo fare A = bianco; B = 
viola

**Comment by gpozzan** [comment]
2015-07-01 12:22 GMT+02:00 Filippo Sestini <notifications@github.com>:

> Ma non possiamo scegliere due colori, A e B, e contornare le immagini con
> * A se clickabile
> * B se già visitata
> * nulla se non cliccabili
> ?
>
> Per rimanere coerenti con i link testuali, potremmo fare A = bianco; B =
> viola
>

Anche questo me gusta, anche perché c'è il clue visivo e non solo "di
colore" quando si passa per la prima volta sopra un'immagine cliccabile.

**Comment by acavestro** [comment]
> Per rimanere coerenti con i link testuali, potremmo fare A = bianco; B =

È già così, ma diventa bianco solo quando ci passi sopra,

**Comment by fsestini** [comment]
Btw, as a user, mi piacerebbe essere in grado di riconoscere le immagini 
cliccabili da quelle non cliccabili alla sola vista, senza dover passare 
il mouse sopra ogni singola immagine.
Riserverei quindi il bordo solo per quelle cliccabili, e cambiare colore 
in caso di non visitato/già visitato. Altri effetti sono secondari e ci 
possiamo pensare in un secondo momento, al limite.

**Comment by acavestro** [comment]
Dunque, potremmo fare:

* cliccabile: bianco
* hover: nero
* visited: viola
* non cliccabile: no bordo.

ACK?

**Comment by gpozzan** [comment]
ACK

**Comment by inrace** [comment]
Perfetto.
Il 01/lug/2015 12:45, "gpozzan" <notifications@github.com> ha scritto:

> ACK
>

**Comment by fsestini** [comment]
E fare hover grigio, come i bottoni testuali?

**Comment by acavestro** [comment]
Provate ora, vediamo se ci siamo.

Also: la navbar è un caso a parte, non bisogna diversificare il colore per i visited, vero? (Ditemi di no, viene un obrobrio)

**Comment by inrace** [comment]
No non serve. Oltre ad essere brutto é pure stupida come cosa, perché se
aggiorni la pagina concerti non ha senso che il link che ti porta li sia
segnalato come giá visitato anche se la pagina é diversa.

Anche il gruppo di sebastiano non l'ha fatto e l'ha specificato nella
relazione
Il 01/lug/2015 13:38, "acavestro" <notifications@github.com> ha scritto:

**Comment by acavestro** [comment]
Perfetto, allora se mi dite che così va bene chiudo.

**Comment by inrace** [comment]
non ho capito, le immagini clickabili non dovrebbero avere il bordo bianco anche se non ci vado sopra con il mouse?

**Comment by acavestro** [comment]
Accidenti, qualcosa non va

**Comment by acavestro** [comment]
Corretto, scusate, avevo ottimizzato il codice e mi era scappata roba vecchia..
