### ISSUE TITLE
Fare footer.

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#6]
Ci starebbe bene un footer con i loghi "w3c compliant" e magari una mail per contattare il gruppo (non esiste, la possiamo creare noi su gmail senza problemi comunque).

**Comment by fsestini** [comment]
Questo è più tricky del previsto. Il div #main-content è posizionato in modo assoluto, e questo rende molto difficile (se non impossibile, ma non si sa mai) posizionare ulteriori div sotto di esso.

**Comment by fsestini** [comment]
Mi metto a lavorare al css per far funzionare il tutto.

**Comment by acavestro** [comment]
Mettiti in pausa che ci sto lavorando pure io.

**Comment by acavestro** [comment]
93d896dafc0c074fd029e13d7d112f38f91af48d risolve il problema

**Comment by fsestini** [comment]
Ormai lo avevo fatto pure io in locale.

**Comment by acavestro** [comment]
Mi piace!

Io pensavo di metterlo sotto, nella parte nera, però anche così non sta male. Bravo! :)
