### ISSUE TITLE
Pulsante "back to the top"

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#7]
Ci starebbe bene, almeno per le pagine con tanto scroll (ma a sto punto si può mettere su tutte le pagine) un pulsante che appaia quando si scrolla oltre la prima schermata e permetta di tornare al top (il classico pulsante che appare sul fondo dello schermo e rimane lì fisso).

La versione non javascript di questo potrebbe essere un link al top sul footer.

**Comment by acavestro** [comment]
Fatto tutto senza javascript.

**Comment by fsestini** [comment]
La versione non javascript probabilmente te la asfalto perché stavo già lavorando al footer, e non ha senso che mi metta a risolvere merge conflict per due tag in croce.

**Comment by acavestro** [comment]
Vai tranquillo, è un link a con href="#top"

**Comment by acavestro** [comment]
(non esistono versioni javascript, basta quella)

**Comment by fsestini** [comment]
Gabriele parlava di una versione javascript che "appare" dopo lo scroll di una pagina. Anche secondo me comunque possiamo farci bastare tranquillamente quella non-. Non abbiamo pagine kilometriche.

**Comment by acavestro** [comment]
:+1:
