### ISSUE TITLE
Finire Home Page

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#8]
Il codice html più o meno dovrebbe esserci, bisogna css-arlo e mettere nella index.html un semplice http-equiv che redirecti direttamente alla pagina cgi (poi volendo sistemare i link interni in modo che puntino direttamente a cgi).

**Comment by fsestini** [comment]
Ma serve veramente l'home page? Ok che la cosa potrebbe essere perché ci sono pochi contenuti, ma mi sembra che replichi i contenuti del sito senza particolare valore aggiunto.

**Comment by acavestro** [comment]
Hai mai visto un sito web senza home page?

**Comment by fsestini** [comment]
Certo che no. La mia idea di usare la pagina Storia come home page.
Parlo dei contenuti della home page, non della home page in sé.

**Comment by inrace** [comment]
Basta anche solo una foto e i link ai social credo, più che altro non
abbiamo gli mp3 delle canzoni...
Il 28/giu/2015 11:14, "Filippo Sestini" <notifications@github.com> ha
scritto:

**Comment by acavestro** [comment]
Non possiamo usare la pagina Storia, ha troppo contenuto specifico che sta bene nella sua pagina.

Ci mettiamo:

* una frase introduttiva
* una immagine
* il prossimo concerto (o i prossimi x)
* foto a caso della galleria
* link a social vari

Però dobbiamo farla sta pagina e anche fatta bene, o non la prendiamo mica la sufficienza.

**Comment by acavestro** [comment]
@fsestini @gpozzan @inrace 

Ho fatto l'home page.
Ditemi che ne pensate.

Ora mostra: una foto random e il prossimo concerto (ne ho aggiunto uno futuro, fittizio).
Piccola, piuttosto pulita e le informazioni più importanti sono, come dice la Gaggi, *above the fold*.

Fatto anche la media query.

**Comment by fsestini** [comment]
> On Jun 29, 2015, at 8:08 PM, acavestro <notifications@github.com> wrote:
> 
> @fsestini @gpozzan @inrace
> 
> Ho fatto l'home page.
> Ditemi che ne pensate.

Niente male! Bella l’idea del prossimo concerto.
Unica cosa, non mi piace la rientranza dell’immagine random.

**Comment by acavestro** [comment]
Mi piacerebbe allinearla a sinistra, ma sto avendo dei problemi, lol

**Comment by acavestro** [comment]
Come non detto, fatto.

**Comment by acavestro** [comment]
Se per voi va bene, chiudo.
