### ISSUE TITLE
Usabilità pagina elenco concerti.

### ISSUE THREAD

**Issue by gpozzan** [tecweb-codedeck/repoosceno#9]
Questa è solo una wild guess mia, quindi se è una cazzata chiudete pure la issue e no problem.

Secondo me nella pagina che mostra la lista dei concerti dovrebbe essere cliccabile tutta la riga di un singolo concerto (quindi il rettangolo che comprende la thumbnail della locandina a destra, la data a sinistra ecc.) questo perché la gente tendenzialmente prova a cliccare le immagini quindi mi immagino già l'utente che prima ancora di vedere il link ai dettagli va a cliccare sulla foto e poi sulla data.

Se riusciamo ad evidenziare bene il fatto che sia cliccabile (ad esempio con un bordo dinamico che appare quando ci si passa sopra col mouse, o qualcosa del genere) dovrebbe essere più semplice.

Se no si può tenere il pulsante dei dettagli ma rendere cliccabili anche data e immagine, per sicurezza.

Però vedete voi, magari è na cazzata :)

**Comment by acavestro** [comment]
Francamente, me ne sbatterei.

@fsestini @inrace ?

**Comment by acavestro** [comment]
ping

**Comment by fsestini** [comment]
Pure io me ne sbatterei sinceramente

**Comment by inrace** [comment]
Avevo controllato, se non ricordo male c'é il tasto "dettagli". Mettere
tutta la riga clickabile mi sembra invalidi il senso del tasto. C'é il
rischio che l'utente tenti entrambi pensando che portino a 2 contenuti
diversi a mio parere.
Il 01/lug/2015 14:02, "Filippo Sestini" <notifications@github.com> ha
scritto:

**Comment by gpozzan** [comment]
No problem, era solo un dettaglio che probabilmente la Gaggi neanche
noterebbe o non apprezzerebbe, vada per lo sbattersene :) (neanche detto
che sia giusto eh, ma quello che ricordo da tecweb 2 è "FATE PULSANTI
GRANDI PER CARITA' CHE LA GGGGENTE NON E' CAPACE DI MIRARE")

2015-07-01 14:10 GMT+02:00 inrace <notifications@github.com>:

**Comment by acavestro** [comment]
Al diavolo la legge di Fitts, lol. 
Ce ne sbattiamo.
